### ISSUE TITLE
Unable to fetch SampleData WeatherForecasts

### ISSUE THREAD

**Issue by tjmcdonough** [DaniJG/ASPCoreVueCLITemplates#2]
First of all great project, I am looking to use this in a production environment but I am running your alternative-spa-template and the line return fetch('/api/SampleData/WeatherForecasts') does not work, I get a SampleApi.vue?undefined:25 GET http://localhost:55031/api/SampleData/WeatherForecasts 400 (Bad Request). 

Are you able to find out why this is happening, please? On my project which is based on this, I get a 404 error so I am missing something in the setup, do you know what this could be? Do you use CORS?

**Comment by DaniJG** [comment]
Just had a quick look, and I could repro. I see the following error in the console:
```
Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware[0]
      'MS-ASPNETCORE-TOKEN' does not match the expected pairing token 'cf5762d8-05ca-4253-9ee0-89609aa982dd', request rejected.
```
Will do some research, might be related with ASP.NET Core 3.0 and/or VS2019. 

You can still run it if instead of the IISExpress profile you use the kestrel one (or execute `dotnet run` in the console.)

Btw, I am leaning more and more towards independently start each server (run dotnet either from VS or `dotnet run` and the vue development server from `npm run serve`), then setup a proxy in one of these 2 ways:
- Add the URL of the dotnet server in vue.config.js
- Add the URL of the vue development server in the startup class using  using `spa.useProxyToDevelopmentServer("http://localhost:8080")`

**Comment by DaniJG** [comment]
Looks like the address passed to the vue development server proxy by VueDevelopmentServerMiddleware is wrong:
```
var addresses = appBuilder.ServerFeatures.Get<IServerAddressesFeature>().Addresses;
```

That line was attempting to avoid hardcoding the URL where the ASP.NET Core server will be listening to...

**Comment by tjmcdonough** [comment]
Thank you very much for fixing. I upgraded this project to 3.0 but it still didn't work. Was there anything else you changed apart from the standard 2.2 > 3.0 migration code in StartUp?

**Comment by tjmcdonough** [comment]
I managed to migrate my application based on this and it all works perfectly. thank you and I will close the issue.
